Add: Authentication to all the Get lambda's
Real-Dev-Squad/feature-flag-backend pull request #129
Opened 2024-12-25 14:02 UTC by MehulKChaudhari

Date: 21/12/2024

Developer Name: @MehulKChaudhari 

---
## Description
This PR will add authentication and cors validation to get Lambda's 

`getAllFeatureFlags`, `GetUserFeatureFlag`, `GetUserFeatureFlags`

### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [ ] Yes
- [x] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

2024-12-29 16:27 UTC, yesyash requested changes

2024-12-29 16:27 UTC, yesyash commented on getAllFeatureFlags/main.go
> +	}
- same as in https://github.com/Real-Dev-Squad/feature-flag-backend/pull/128#discussion_r1899158914

2024-12-29 16:27 UTC, yesyash commented on getAllFeatureFlags/main.go
> +	}
- same as in https://github.com/Real-Dev-Squad/feature-flag-backend/pull/128#discussion_r1899158965

2024-12-29 16:27 UTC, yesyash commented on getUserFeatureFlag/main.go
> +	}
- same as above

2024-12-29 16:27 UTC, yesyash commented on getUserFeatureFlags/main.go
> +	}
- same as above

2025-01-03 17:30 UTC, yesyash approved these changes

2025-01-05 17:30 UTC, lakshayman approved these changes

2025-01-05 17:37 UTC, merged