Add: Authentication create and update featureFlag lambda's
Real-Dev-Squad/feature-flag-backend pull request #130
Opened 2024-12-28 15:23 UTC by MehulKChaudhari

Date: 28/12/2024

Developer Name: @MehulKChaudhari 

---
## Description
This PR will add authentication and cors validation to update Lambda's 

`updateFeatureFlag`, `updateUserFeatureFlag`, `createUserFeatureFlags`,  `createFeatureFlags`

### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [ ] Yes
- [x] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

2024-12-29 16:30 UTC, yesyash requested changes

2024-12-29 16:30 UTC, yesyash commented on createFeatureFlag/main.go
> +	}
- same comment from: 
    - https://github.com/Real-Dev-Squad/feature-flag-backend/pull/128#discussion_r1899158914
    - https://github.com/Real-Dev-Squad/feature-flag-backend/pull/128#discussion_r1899158965

2024-12-29 16:30 UTC, yesyash commented on createUserFeatureFlag/main.go
> +	}
- same as above

2024-12-29 16:30 UTC, yesyash commented on resetLimitLambda/main.go
> +	}
- same as above

2024-12-29 16:30 UTC, yesyash commented on updateFeatureFlag/main.go
> +	}
- same as above

2024-12-29 16:30 UTC, yesyash commented on updateUserFeatureFlag/main.go
> +	}
- same as above

2025-01-03 17:32 UTC, yesyash approved these changes

2025-01-05 17:30 UTC, lakshayman approved these changes

2025-01-05 17:37 UTC, merged